function tag2xls(tag, explog_xls)

[~, animal_name] = fileparts(tag.folder);
date = datestr(tag.start, 'yy_mm_dd');
if tag.enablestim
  xl_data = {tag.Block, '', '', '', '', '' , tag.param_stim.Power, ...
  tag.param_stim.Type, tag.param_stim.Duration, tag.param_stim.Duration_pulse, ...
  tag.param_stim.Freq, tag.param_stim.Chance, ...
  '', tag.param_stim.Count, '', '', '', tag.Experiment date, tag.Duration, ...
  [tag.Notes{:}]};
else
  xl_data = {tag.Block, '', '', '', '', '' , ...
  '', '', '', '', '', tag.Experiment date, num2str(tag.Duration), ...
  [tag.Notes{:}]};
end
warning('off')
xlswrite(explog_xls, xl_data, animal_name, ['A' num2str(tag.Block)])
warning('on')
